/*
  Warnings:

  - You are about to drop the column `status` on the `documents` table. All the data in the column will be lost.

*/
-- CreateEnum
CREATE TYPE "DocumentType" AS ENUM ('SUMMONS', 'SUBPOENA', 'LEGAL_BRIEF', 'MEMORANDUM', 'MOTION', 'COURT_ORDER', 'JUDGMENT', 'HEARING_TRANSCRIPT', 'SERVICE_OF_PROCESS', 'APPEAL', 'INJUNCTION', 'ARBITRATION_AWARD', 'MANDATE_CONTRACT', 'COMMERCIAL_CONTRACT', 'TRANSFER_DEED', 'LEASE_AGREEMENT', 'NOTARIAL_ACT', 'NDA', 'SETTLEMENT_AGREEMENT', 'ARTICLES_OF_INCORPORATION', 'SHAREHOLDER_AGREEMENT', 'EMPLOYMENT_CONTRACT', 'IDENTITY_DOCUMENT', 'COMPANY_REGISTRATION', 'POWER_OF_ATTORNEY', 'PROOF_OF_ADDRESS', 'BANK_CERTIFICATE', 'INVOICE', 'ESCROW_STATEMENT', 'EXPENSE_REPORT', 'FINANCIAL_REPORT', 'TAX_DECLARATION', 'PAYMENT_RECEIPT', 'EXHIBIT', 'BAILIFF_REPORT', 'EXPERT_REPORT', 'WRITTEN_TESTIMONY', 'PHOTO_VIDEO_EVIDENCE', 'COMMUNICATION_RECORDS', 'MEDICAL_REPORT', 'POLICE_REPORT', 'FORMAL_NOTICE', 'CLIENT_LETTER', 'OPPOSING_PARTY_LETTER', 'COURT_CORRESPONDENCE', 'ARCHIVED_EMAIL', 'REGISTERED_LETTER', 'FEE_AGREEMENT', 'CLIENT_INTAKE_FORM', 'MISSION_AGREEMENT', 'INTERNAL_REPORT', 'MEETING_MINUTES', 'LEGAL_RESEARCH_NOTE', 'DOCUMENT_TEMPLATE', 'TRADEMARK_FILING', 'PATENT', 'LICENSE_AGREEMENT', 'REGULATORY_AUTHORIZATION', 'COMPLIANCE_CERTIFICATE');

-- AlterTable
ALTER TABLE "documents" DROP COLUMN "status",
ADD COLUMN     "type" "DocumentType" NOT NULL DEFAULT 'INTERNAL_REPORT';

-- DropEnum
DROP TYPE "DocumentStatus";
