import { IsEnum, IsInt, IsOptional, IsPositive, IsString, IsUUID } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export enum DocumentStatus {
  UPLOADED = 'UPLOADED',
  OCR_PENDING = 'OCR_PENDING',
  OCR_DONE = 'OCR_DONE',
  INDEXED = 'INDEXED',
  ERROR = 'ERROR',
}

export enum DocumentType {
  SUMMONS = 'SUMMONS',
  SUBPOENA = 'SUBPOENA',
  LEGAL_BRIEF = 'LEGAL_BRIEF',
  MEMORANDUM = 'MEMORANDUM',
  MOTION = 'MOTION',
  COURT_ORDER = 'COURT_ORDER',
  JUDGMENT = 'JUDGMENT',
  HEARING_TRANSCRIPT = 'HEARING_TRANSCRIPT',
  SERVICE_OF_PROCESS = 'SERVICE_OF_PROCESS',
  APPEAL = 'APPEAL',
  INJUNCTION = 'INJUNCTION',
  ARBITRATION_AWARD = 'ARBITRATION_AWARD',
  MANDATE_CONTRACT = 'MANDATE_CONTRACT',
  COMMERCIAL_CONTRACT = 'COMMERCIAL_CONTRACT',
  TRANSFER_DEED = 'TRANSFER_DEED',
  LEASE_AGREEMENT = 'LEASE_AGREEMENT',
  NOTARIAL_ACT = 'NOTARIAL_ACT',
  NDA = 'NDA',
  SETTLEMENT_AGREEMENT = 'SETTLEMENT_AGREEMENT',
  ARTICLES_OF_INCORPORATION = 'ARTICLES_OF_INCORPORATION',
  SHAREHOLDER_AGREEMENT = 'SHAREHOLDER_AGREEMENT',
  EMPLOYMENT_CONTRACT = 'EMPLOYMENT_CONTRACT',
  IDENTITY_DOCUMENT = 'IDENTITY_DOCUMENT',
  COMPANY_REGISTRATION = 'COMPANY_REGISTRATION',
  POWER_OF_ATTORNEY = 'POWER_OF_ATTORNEY',
  PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS',
  BANK_CERTIFICATE = 'BANK_CERTIFICATE',
  INVOICE = 'INVOICE',
  ESCROW_STATEMENT = 'ESCROW_STATEMENT',
  EXPENSE_REPORT = 'EXPENSE_REPORT',
  FINANCIAL_REPORT = 'FINANCIAL_REPORT',
  TAX_DECLARATION = 'TAX_DECLARATION',
  PAYMENT_RECEIPT = 'PAYMENT_RECEIPT',
  EXHIBIT = 'EXHIBIT',
  BAILIFF_REPORT = 'BAILIFF_REPORT',
  EXPERT_REPORT = 'EXPERT_REPORT',
  WRITTEN_TESTIMONY = 'WRITTEN_TESTIMONY',
  PHOTO_VIDEO_EVIDENCE = 'PHOTO_VIDEO_EVIDENCE',
  COMMUNICATION_RECORDS = 'COMMUNICATION_RECORDS',
  MEDICAL_REPORT = 'MEDICAL_REPORT',
  POLICE_REPORT = 'POLICE_REPORT',
  FORMAL_NOTICE = 'FORMAL_NOTICE',
  CLIENT_LETTER = 'CLIENT_LETTER',
  OPPOSING_PARTY_LETTER = 'OPPOSING_PARTY_LETTER',
  COURT_CORRESPONDENCE = 'COURT_CORRESPONDENCE',
  ARCHIVED_EMAIL = 'ARCHIVED_EMAIL',
  REGISTERED_LETTER = 'REGISTERED_LETTER',
  FEE_AGREEMENT = 'FEE_AGREEMENT',
  CLIENT_INTAKE_FORM = 'CLIENT_INTAKE_FORM',
  MISSION_AGREEMENT = 'MISSION_AGREEMENT',
  INTERNAL_REPORT = 'INTERNAL_REPORT',
  MEETING_MINUTES = 'MEETING_MINUTES',
  LEGAL_RESEARCH_NOTE = 'LEGAL_RESEARCH_NOTE',
  DOCUMENT_TEMPLATE = 'DOCUMENT_TEMPLATE',
  TRADEMARK_FILING = 'TRADEMARK_FILING',
  PATENT = 'PATENT',
  LICENSE_AGREEMENT = 'LICENSE_AGREEMENT',
  REGULATORY_AUTHORIZATION = 'REGULATORY_AUTHORIZATION',
  COMPLIANCE_CERTIFICATE = 'COMPLIANCE_CERTIFICATE',
  OTHER = 'OTHER',
}

export class CreateDocumentDto {
  @ApiProperty() @IsString() title: string;
  @ApiProperty() @IsString() fileName: string;
  @ApiProperty() @IsString() fileUrl: string;
  @ApiProperty() @IsString() fileType: string;
  @ApiProperty() @IsInt() @IsPositive() fileSize: number;
  @ApiPropertyOptional() @IsOptional() @IsString() category?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() caseId?: string;
}

export class UpdateDocumentDto {
  @ApiPropertyOptional() @IsOptional() @IsString() title?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() category?: string;
  @ApiPropertyOptional({ enum: DocumentType }) @IsOptional() @IsEnum(DocumentType) type?: DocumentType;
  @ApiPropertyOptional({ enum: DocumentStatus }) @IsOptional() @IsEnum(DocumentStatus) status?: DocumentStatus;
}
